Install Pytorch in windows

In [ ]:
! pip3 install torch torchvision torchaudio

import pytorch library using torch keyword

In [1]:
import torch

c:\Users\yadav\AppData\Local\Programs\Python\Python38\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


create a tensor

In [4]:
t1 = torch.tensor(4.)
print(t1)
print(t1.dtype)

tensor(4.)
torch.float32


In [5]:
t2 = torch.tensor(2)
print(t2)
print(t2.dtype)

tensor(2)
torch.int64


vector or 1d matrix

In [6]:
t3 = torch.tensor([1.,2,3.4])
print(t3)
print(t3.dtype)

tensor([1.0000, 2.0000, 3.4000])
torch.float32


Matrix

In [7]:
t4 = torch.tensor([[5.,6],
[7,8],
[9,10]])
print(t4)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


In [9]:
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([])
torch.Size([])
torch.Size([3])
torch.Size([3, 2])


In [14]:
t5 = torch.tensor(["2", "3",])

ValueError: too many dimensions 'str'

In [15]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [22]:
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [23]:
y.backward()

In [24]:
print("dy/dx:", x.grad)
print("dy/dw:", w.grad)
print("dy/db:", b.grad)

dy/dx: None
dy/dw: tensor(6.)
dy/db: tensor(5.)


In [25]:
t6 = torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [27]:
t7 = torch.cat((t4,t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [29]:
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [30]:
t9 = t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

In [31]:
import numpy as np

x = np.array([[1,2],
[3,4]])

x

array([[1, 2],
       [3, 4]])

In [32]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [33]:
x.dtype, y.dtype

(dtype('int32'), torch.int32)

Dataset and DataLoader

In [34]:
from torch.utils.data import TensorDataset

In [ ]:
train_ds = TensorDataset(input)