In [3]:
import torch
import numpy as np

In [4]:
lst = [3,4,5,6]
arr = np.array(lst)

In [5]:
arr.dtype

dtype('int32')

Convert Numpy To Pytorch Tensors

In [6]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [7]:
tensors[:2]

tensor([3, 4], dtype=torch.int32)

In [8]:
tensors[3] = 100

In [9]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

disadvantage of from_numpy. The array and tensor uses the same memory location

In [10]:
arr

array([  3,   4,   5, 100])

In [11]:
tensors_arr = torch.tensor(arr)

In [17]:
tensors_arr[1] = 200
tensors_arr

tensor([  3, 200, 200, 100], dtype=torch.int32)

In [18]:
arr

array([  3,   4, 200, 100])

In [19]:
torch.zeros(2,3,dtype = torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [20]:
torch.ones(2,3, dtype = torch.int64)

tensor([[1, 1, 1],
        [1, 1, 1]])